### ISSUE TITLE
如何使electron能够联合nestjs的微服务同时运行

### ISSUE THREAD

**Issue by CloudWoR** [Doubleshotjs/template-vue-nest#15]
我在electron-vue-nest模板中，想要同时开发nestjs的微服务来实现分布式服务，我大概看了一下template-vue-nest的模板和template-nestjs-microservices模板，虽然大概明白doubleshotjs做了什么，但是还是无法自己实现如何在template-vue-nest模板中实现和template-nestjs-microservices中一样的功能。我看template-vue-nest中，引入的是“@dobleshotjs/builder”中的defineConfig，而“@dobleshotjs/runner”中的defineConfig。

**Comment by renjietan** [comment]
大佬 这个模板中，继承sqlite数据库  总是会出现各种版本问题  electron的版本要做降级处理的话，不知道是否框架还能正常运行

**Comment by ArcherGu** [comment]
> 大佬 这个模板中，继承sqlite数据库 总是会出现各种版本问题 electron的版本要做降级处理的话，不知道是否框架还能正常运行

你用的什么sqlite库呢？
